[package]
name = "split-the-bob"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
fjall = "2.11.2"
serde = "1.0.228"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
